version: '3.8'
services:
  db:
    image: "postgres:latest"
    container_name: "book_db"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookShop
    ports:
      - "5432:5432"
